version: '3.4'

services:
  hngx:
    image: ${DOCKER_REGISTRY-}hngx
    container_name: hngx_container
    build:
      context: .
      dockerfile: HNGx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - hnghdb
    environment:
      ConnectionStrings__DefaultConnection: "Host=hnghdb;Database=postgres;Username=postgres;Password=postgres"
  hnghdb:
    container_name: hnghdb
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}